import dotenv from "dotenv";
import assert from "assert";

dotenv.config();

const {
  PORT,
  HOST,
  HOST_URL,
  API_KEY,
  AUTH_DOMAIN,
  PROJECT_ID,
  STORAGE_BUCKET,
  MESSAGING_SENDER_ID,
  APP_ID,
  GOOGLE_ID_TOKENSENDPULSE_API_USER_ID,
  SENDPULSE_API_SECRET,
  SENDPULSE_TOKEN_STORAGE,
  SENDPULSE_API_USER_ID,
  KIWI_API_KEY,
  RESEND_API_KEY,
  SMTP_PROJECT_ID,
  SMTP_SENDER_ADDRESS,
  SMTP_PROJECT_SECRET,
  PAYSTACK_TEST_SECRET_KEY,
  PAYSTACK_TEST_PUBLIC_KEY,
  GOOGLE_CALENDER_CLIENT_ID,
  GOOGLE_CALENDER_SECRET,
  MAILERLITE_API_KEY,
  MAILERLITE_VERIFIED_EMAIL,
} = process.env;

assert(PORT, "Port is required");
assert(HOST, "Host is required");


export default {
  port: PORT,
  host: HOST,
  hostUrl: HOST_URL,
  firebaseConfig: {
    apiKey: API_KEY,
    authDomain: AUTH_DOMAIN,
    projectId: PROJECT_ID,
    storageBucket: STORAGE_BUCKET,
    messagingSenderId: MESSAGING_SENDER_ID,
    appId: APP_ID,
  },
  GOOGLE_ID_TOKENSENDPULSE_API_USER_ID,
  SENDPULSE_API_SECRET,
  SENDPULSE_TOKEN_STORAGE,
  SENDPULSE_API_USER_ID,
  KIWI_API_KEY,
  RESEND_API_KEY,
  SMTP_PROJECT_ID,
  SMTP_SENDER_ADDRESS,
  SMTP_PROJECT_SECRET,
  PAYSTACK_TEST_SECRET_KEY,
  PAYSTACK_TEST_PUBLIC_KEY,
  GOOGLE_CALENDER_CLIENT_ID,
  GOOGLE_CALENDER_SECRET,
  MAILERLITE_API_KEY,
  MAILERLITE_VERIFIED_EMAIL,
};
